Middlewares
dilyara4949/employees-api pull request #3
Opened 2024-06-03 08:09 UTC by dilyara4949

Added 3 middlewares: 
Logger - logs all incoming requests
Timer - logs time taken for each request
CorrelationID - adds correlation id to each request context

All middlewares wrapped by Adap function

2024-06-03 10:50 UTC, krylphi requested changes

2024-06-03 10:50 UTC, krylphi commented on cmd/main.go
> +	configs := config.NewConfig()
`config` here is the correct term, as we use 1 config to hava several parameters

2024-06-03 10:50 UTC, krylphi commented on cmd/main.go
>  	err := http.ListenAndServe(":8080", mux)
nit: You probably want to have `address` and `port` in config also

2024-06-03 10:50 UTC, krylphi commented on constants.go
> +const CorrelationID = "X-Correlation-ID"
You don't need to have separated package/file for constants most of the times. You should define them where you use them. In this case it would probably be better placed in `middleware`

2024-06-03 10:50 UTC, krylphi commented on internal/middleware/adapter.go
> +func Adapt(endpoint http.HandlerFunc, middlewares ...Adapter) http.HandlerFunc {
As this is `chain of responsibility` pattern, I think it should be named `Chain` or something similar

2024-06-03 10:50 UTC, krylphi commented on internal/middleware/adapter.go
> +type Adapter func(http.Handler) http.HandlerFunc
This is more like `Middleware` type, than `Adapter`.

2024-06-03 10:50 UTC, krylphi commented on internal/route/setup.go
> +	mux.HandleFunc("GET /positions/{id}", middleware.Adapt(auth.Auth(positionsController.GetPosition), middleware.Logger(), middleware.Timer(), middleware.CorrelationIDMiddleware()))
You can optimize the chain as we discussed on the call

2024-06-03 11:10 UTC, dilyara4949 commented on cmd/main.go
> +	configs := config.NewConfig()
got it, it was overlapping with package name, i should make alias to package then

2024-06-03 11:15 UTC, dilyara4949 commented on cmd/main.go
>  	err := http.ListenAndServe(":8080", mux)
what is `address` in this case?   `/`?

2024-06-04 08:38 UTC, krylphi reviewed
Good job overall. Only fer small corrections

2024-06-04 08:38 UTC, krylphi commented on internal/route/setup.go
> +func LogCorrelationIDTimer(endpoint http.HandlerFunc, JWTTokenSecret string) http.HandlerFunc {
No need for this function to be exported (name starts with capital letter), IMO, because it will be used only here.

2024-06-04 08:38 UTC, krylphi commented on internal/config/config.go
>  	config.JWTTokenSecret = os.Getenv("JWTTokenSecret")
names of env variables should be all capital with underscore delimiter. like `JWT_TOKEN_SECRET`.

2024-06-04 08:38 UTC, krylphi commented on internal/config/config.go
>  func NewConfig() Config {
consider config validation. If required values are empty, return error.

2024-06-04 08:38 UTC, krylphi commented on internal/route/setup.go
> +	mux.HandleFunc("GET /positions/{id}", middleware.Adapt(auth.Auth(positionsController.GetPosition), middleware.Logger(), middleware.Timer(), middleware.CorrelationIDMiddleware()))
done

2024-06-04 08:38 UTC, krylphi commented on internal/middleware/adapter.go
> +type Adapter func(http.Handler) http.HandlerFunc
Fixed

2024-06-04 08:38 UTC, krylphi commented on internal/middleware/adapter.go
> +func Adapt(endpoint http.HandlerFunc, middlewares ...Adapter) http.HandlerFunc {
Fixed

2024-06-04 08:40 UTC, krylphi commented on cmd/main.go
>  	err := http.ListenAndServe(":8080", mux)
it should also be in config. By default you can use either `127.0.0.1` or preferably `0.0.0.0`

2024-06-04 08:40 UTC, krylphi commented on cmd/main.go
> +	configs := config.NewConfig()
You can shorten var name to `cfg`

2024-06-04 09:14 UTC, krylphi commented on constants.go
> +const CorrelationID = "X-Correlation-ID"
Fixed

2024-06-04 09:14 UTC, krylphi commented on internal/route/setup.go
> +func LogCorrelationIDTimer(endpoint http.HandlerFunc, JWTTokenSecret string) http.HandlerFunc {
Fixed

2024-06-04 10:26 UTC, krylphi approved these changes

2024-06-04 10:36 UTC, merged